### ISSUE TITLE
Add SPM support

### ISSUE THREAD

**Issue by tyten** [socure-inc/socure-sigmadevice-sdk-ios#2]
The library does not have a `Package.swift` defined for SPM support. Please add this.

[Distributing binary frameworks as packages](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages)

**Comment by buraksocure** [comment]
Thank you @tyten We are working on this and will provide SPM support.

**Comment by iuriipleskach** [comment]
Hi @buraksocure,
Thank you, I see SPM support is merged to main. Could you please release it, so we can use a released/tagged version of the SDK?

**Comment by buraksocure** [comment]
Hi @iuriipleskach Thanks for following up. Yes, It's already released. You can use this file (https://github.com/socure-inc/socure-sigmadevice-sdk-ios/blob/main/Package.swift) to add it through package manager on Xcode. Please try and let me know if you need further assistance. You can reach out from dse@socure.com

**Comment by iuriipleskach** [comment]
@buraksocure, everything works fine if I add SPM dependency to `main` branch. But the latest 2.0.0 release doesn't have Package.swift, so I can't add versioned dependency. 
Could you please make e.g. 2.0.1 tag/release containing `Package.swift`?

**Comment by buraksocure** [comment]
Hi @iuriipleskach Thanks for following up but I don't think that I understand your request.

Package.swift is already looking at 2.0.0 which is our latest version -> https://github.com/socure-inc/socure-sigmadevice-sdk-ios/blob/main/Package.swift#L18

Line 18 looks at Frameworks/DeviceRisk.xcframework which is our 2.0.0 -> https://github.com/socure-inc/socure-sigmadevice-sdk-ios/blob/main/Framework/DeviceRisk.xcframework/ios-arm64/DeviceRisk.framework/Info.plist

Feel free to reach out through dse@socure.com if you like to discuss further.

**Comment by edelabar** [comment]
I'm with @iuriipleskach on this one, `Package.swift` was added in fd8fe9ccc063966a7a5c9e15cbe46a9f727c66a9, which is [after the 2.0.0 release tag](https://github.com/socure-inc/socure-sigmadevice-sdk-ios/compare/2.0.0...main). 

If you tag `main` with `2.0.1` now it will enable Swift Package Manager with a version number instead of a branch.

E.g. we, the package consumers, can use this:

``` swift
    dependencies: [
        .package(url: "https://github.com/socure-inc/socure-sigmadevice-sdk-ios.git", from: "2.0.0"),
    ],
```

instead of this:

``` swift
    dependencies: [
        .package(url: "https://github.com/socure-inc/socure-sigmadevice-sdk-ios.git", branch: "main"),
    ],
```

Without the tag, we'd simply be running off the latest `main` branch which could be in-between release versions from your perspective, and does not pin us to specific, testable versions of your library.

**Comment by buraksocure** [comment]
Thank you! @edelabar I received your email and replied.

**Comment by pavan-mellamputi-socure** [comment]
@edelabar @iuriipleskach - hey folks, I tagged the latest version as `2.0.1`, can you please confirm that it now works as expected, thanks.

**Comment by buraksocure** [comment]
Hi @edelabar and @iuriipleskach FYI - We added the tag so you can consume the package easily. Thank you! 

https://github.com/socure-inc/socure-sigmadevice-sdk-ios/releases/tag/2.0.1

**Comment by iuriipleskach** [comment]
Works as expected, thank you!
